# 中秋节活动时间段，格式 yyyy.MM.dd.HH:mm-yyyy.MM.dd.HH:mm
# 例如：2026.9.25.00:00-2026.9.27.23:59（26年中秋节时间段）
event-time: "2026.9.25.00:00-2026.9.27.23:59"

# 普通生物（猪、僵尸、蛙鱼、末影螨、玩家等）掉落月饼的概率，取值范围 0.0 ~ 1.0
passive-mob-drop-chance: 0.2
# 末影龙掉落龙骨月饼概率，取值范围 0.0 ~ 1.0（默认百分百掉落）
dragon-drop-chance: 1.0
# 凋零掉落凋零月饼概率，取值范围 0.0 ~ 1.0（默认百分百掉落）
wither-drop-chance: 1.0